-- MySQL Script generated by MySQL Workbench
-- Sun Jun 23 23:22:27 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema diabets-quiz
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema diabets-quiz
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `diabets-quiz` DEFAULT CHARACTER SET utf8 ;
USE `diabets-quiz` ;

-- -----------------------------------------------------
-- Table `diabets-quiz`.`quiz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diabets-quiz`.`quiz` (
  `id` INT UNSIGNED NOT NULL,
  `gender` VARCHAR(45) NULL,
  `age` VARCHAR(45) NULL,
  `bmi` VARCHAR(45) NULL,
  `waist` VARCHAR(45) NULL,
  `use_blood_medication` TINYINT(1) NULL,
  `history_high_blood_glucose` TINYINT(1) NULL,
  `physical_activity` TINYINT(1) NULL,
  `vegetables_fruit_consumption` TINYINT(1) NULL,
  `family_history_diabetes` VARCHAR(45) NULL,
  `created_on` TIMESTAMP NULL,
  `quizcol` VARCHAR(45) NULL DEFAULT 'NOW()',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
